### ISSUE TITLE
EventCallback re-rendering indefinitely 

### ISSUE THREAD

**Issue by Denny09310** [Dreamescaper/BlazorBindings.Maui#154]
>This issue is a follow-up to PR #150.

As mentioned in the title, I've discovered that `EventCallbacks` are entering an infinite loop, continuously calling themselves. In [this example](https://github.com/user-attachments/files/17533199/App2.zip), I only attached the `OnLoaded` event to the `OnCounterClicked` event, which causes the app to get stuck on the SplashScreen. If you set a breakpoint inside the function, you'll see it's called repeatedly without end. I tested this on Android and Windows but haven’t tried it on Apple devices (macOS or iOS) due to limited access.

**Comment by Dreamescaper** [comment]
I see. So the issue here is not only about EventCallbacks on themselves, but about `Loaded` event in MAUI as well.
It invokes the event handler right in event `add`:
https://github.com/dotnet/maui/blob/f269ef3de701043910c941bbbfcbdb7422cc245c/src/Controls/src/Core/VisualElement/VisualElement.cs#L2203

And that contributes to this infinite loop.

**Comment by Denny09310** [comment]
I see, but it seems to be solved with that new `Equals` method we implemented. Probably because is not set again after the initialization

**Comment by Dreamescaper** [comment]
Fixed by #150 .
