### ISSUE TITLE
[Q] Attached props

### ISSUE THREAD

**Issue by ParadiseFallen** [Dreamescaper/BlazorBindings.Maui#49]
Hi. i like this project and waiting for official support too.

Whats your thoughts about attached properties? How to impliment em?
It seems attached props will require changes in `Blazor` itself

**Comment by Dreamescaper** [comment]
You're right, Blazor doesn't support attached props natively. Currently this project uses several approaches to overcome this issues:
- emulate attached properties via `CaptureUnmatchedValues`. You can read more about that with examples [here](https://dreamescaper.github.io/MobileBlazorBindingsDocs/maui-blazor-bindings/release-notes/preview-7.html#attached-properties-support).
- use parent element to set attached property value for an element. This approach is used with `GridCell` element, you can take a look at example [here](https://github.com/Dreamescaper/BlazorBindings.Maui/blob/main/samples/ControlGallery/Views/Layouts/GridPage.razor).
- technically the third approach is supported - via child element, currently it is used in `ShellProperties`. But there's no sample as for now, because I don't really like this approach (at least in a currently implemented way).

Neither of those approaches is perfect, but as for now the first approach is the main one. It lacks a proper intelli-sense, but at least it looks fine.

**Comment by Dreamescaper** [comment]
I'm closing the issue, let me know if you have any more questions.
