### ISSUE TITLE
Cannot to get CascadingParam when naviated from  INavigation.PushAsync<>()

### ISSUE THREAD

**Issue by le-nn** [Dreamescaper/BlazorBindings.Maui#90]
Cannot to get CascadingParam when naviated from INavigation.PushAsync<>()

```cs
public record Theme {
    public string Background { get; init; } = ""#ffffffff";
}
```

AppShell
```razor
<CascadingValue Value="Theme">
    <Shell FlyoutIsPresented="true">
        <ShellContent Title="Navigation">
            <PageNavigatedFrom />
        </ShellContent>
        <ShellContent Title="Navigation">
            <PageNavigatedTo />
        </ShellContent>
    </Shell>
</CascadingValue>

@code {
    Theme Theme { get; } = new();
}
```

PageNavigateFrom 
```razor
@inject INavigation Navigation

<ContentPage Padding="12"
             Title="">
    <Button Text="Navigate" OnClick="HandleNavigate" />
</ContentPage>

@code {
    [CascadingParameter]
    Theme? Theme { get; set; }

    void HandleNavigate() {
        Navigation.PushAsync<PageNavigatedTo>();
    }
}
```

PageNavigateTo
```razor
<ContentPage Padding="12"
             Title="">
    <Label Text="@Theme?.Background.ToString()" />
</ContentPage>

@code {
    [CascadingParameter]
    Theme? Theme { get; set; } // Always null
}

```

**Comment by Dreamescaper** [comment]
That's an interesting use case. 

Currently Navigation.PushAsync is equivalent to smth like that from Maui: `Navigation.PushAsync(new PageNavigatedTo())`, i.e. it always creates a new page, in a separate blazor render tree. It doesn't re-use `<ShellContent Title="Navigation"> <PageNavigatedTo />  </ShellContent>` in your Shell file. 

I'll take a look whether it is possible to re-use cascading values from calling component (I doubt it that Blazor allows that, but not sure), it's probably .

I'm thinking about your use case though. Would it work if you register Theme as a singleton in DI container instead of CascadingValue?

**Comment by le-nn** [comment]
In my usecase,
If registering Singleton in DI instead of Cascading Param,
I should handle ```StatehasChanged``` manually in every component with  something like IObservable.
So, I need ```CascadingValue```. (ex:  Changing the App Theme)

When route from nav menu button in ```Shell``` with ```ShellContent``` , it worked fine.

**Comment by Dreamescaper** [comment]
I see. Technically it is possible to handle StateHasChanged in root component only, but again - PushAsync currently creates a separate blazor tree, therefore there is no shared root component.

**Comment by Dreamescaper** [comment]
@le-nn 
I'm thinking to add a support for [layout components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-7.0).  While it doesn't make much sense to define markup there, but it might be useful for [cascading values](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-7.0) or error boundaries.

Do you think it would make sense from the perspective of this request?
